[package]
name = "flow"
version.workspace = true
edition.workspace = true
[[bin]]
name = "flow"
path = "src/main.rs"
[dependencies]
flow-defaults = { path = "../flow-defaults" }
datom-codec = { git = "https://github.com/LiGoldragon/datom-codec", rev = "4dff16b4f7412febc3b71aac8b49680cd20988cb" }
protos = { git = "https://github.com/LiGoldragon/protos", rev = "15b41da8f2579e73ead59bc0c2b97529b8ac32d3" }
rkyv.workspace = true
signal-flow = { workspace = true, features = ["datom"] }
[dev-dependencies]
tempfile = "3"
