[workspace]
members = ["crates/flow-nexus", "crates/flow", "crates/flow-meta"]
resolver = "3"

[workspace.package]
version = "0.3.0"
edition = "2024"
rust-version = "1.89"
license = "MIT OR Apache-2.0"
repository = "https://github.com/LiGoldragon/flow"
publish = false

[workspace.dependencies]
rkyv = { version = "0.8", default-features = false, features = ["std", "bytecheck", "little_endian", "pointer_width_32", "unaligned"] }
serde_json = "1"
thiserror = "2"
signal-flow = { git = "https://github.com/LiGoldragon/signal-flow", rev = "aaac0f07e600bbfb044d3c62aa55d43d41c76cd0" }
meta-signal-flow = { git = "https://github.com/LiGoldragon/meta-signal-flow", rev = "e2841c893b1f1291371e530d42392cfe3e53d44d" }
