[package]
name = "signal-flow"
version = "0.1.0"
edition.workspace = true
[features]
default = []
datom = ["dep:datom-codec", "dep:protos"]
[dependencies]
datom-codec = { git = "https://github.com/LiGoldragon/datom-codec", rev = "09e2a9d52bf7f2f11e51d15cb6c3177f72c6c927", optional = true }
protos = { git = "https://github.com/LiGoldragon/protos", rev = "1febca7836bf8d5f5973a302fdd50aa9c84c159b", optional = true }
rkyv.workspace = true
