[package]
name = "flow-meta"
version.workspace = true
edition.workspace = true
[[bin]]
name = "flow-meta"
path = "src/main.rs"
[dependencies]
datom-codec = { git = "https://github.com/LiGoldragon/datom-codec", rev = "09e2a9d52bf7f2f11e51d15cb6c3177f72c6c927" }
meta-signal-flow = { path = "../meta-signal-flow", features = ["datom"] }
protos = { git = "https://github.com/LiGoldragon/protos", rev = "1febca7836bf8d5f5973a302fdd50aa9c84c159b" }
rkyv.workspace = true
